name: Github Pages 📔

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Push to gh-pages branch
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        pdf_build: true