name: Github Pages 📔

on:
  push:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set outputs
      id: variables
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Push to gh-pages branch
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        asciidoctor_params: -aversion=${{ steps.variables.outputs.sha_short }}
        pdf_build: true